# Markov Chains

##Overview

Markov chains are one of the most fundamental classes of stochastic processes

Attributes

1. simple, flexible and supported by many elegant theoretical results
2. valuable for building intuition about random dynamic models
3. very useful in their own right

Reference

    1. Thomas J. Sargent and John Stachurski, http://quant-econ.net
    2. Richard Weber, http://www.statslab.cam.ac.uk/~rrw1/markov
    3. Eugenia Stoimenova, http://www.math.bas.bg/~jeni/
    4. http://www.tcs.hut.fi/Studies
    5. http://steep.inrialpes.fr/~Arnaud
    6. http://www.philol.msu.ru/~lex/khmelev/published/llc/khmelev.html
    7. 李中傑, 棒球比賽宛如是一個馬可夫過程, 真理大學


   
<div align="center"> Money Ball<br>
<audio controls="" src="audio/show.wav">
</audio></div>

In [1]:
import numpy as np
import scipy as sp
from scipy.linalg import eig
from numpy import cumsum
from numpy.random import uniform
from IPython.display import HTML

In [2]:
def printP(P):
    l='<div align="center"><table>';
    row=len(P[:,0])
    i=j=k=0;
    l=l+"<tr><td>State</td>"
    for k in range(row):
          k1=k+1
          l=l+'<td><div align="center">%s</div></td>' % (k1)
          k++1  
    for i in range(1,row+1):
        l=l+'<tr><td><div align="center">%s</div></td>' %i
        for j in range(1,row+1):
            l=l+"<td> %1.4f </td>" %P[i-1,j-1];
            j++1
        l=l+"</tr>"
        i++1
    l=l+"</table></div>"
    return HTML(l)

In [2]:
def printP2(P,states):
    """
    printP2(P,states):
      input: P, transition probability matrix,
          states, array of all states
      output: well-formated HTML table for the transition Probability matrix       
    """
    #if states:
    #    states=np.arange(size(P[0,]))
    l='<div align="center"><table>';
    row=len(P[:,0])
    i=j=k=0;
    l=l+"<tr><td>State</td>";
    #for n in arange(size(states)):
        
    for k in range(row):
          l=l+'<td><div align="center">%s</div></td>' % (states[k])
          k++1
    l=l+'</tr>';        
    for i in range(1,row+1):
        l=l+'<tr><td><div align="center">%s</div></td>' %states[i-1]
        for j in range(1,row+1):
            l=l+"<td> %1.4f </td>" %P[i-1,j-1];
            j++1
        l=l+"</tr>"
        i++1
    l=l+"</table></div>"
    return HTML(l)

In [3]:
def StableDist(P):
    """
    StableDist(P)
      input: P, transition probability matrix,
      output: stable distribution 
    """
    evals, evecs = sp.linalg.eig(P,left=True,right=False)
    eps=1e-6
    ind=evals[:]>1.-eps
    p0=np.transpose(evecs[:,ind]/sum(evecs[:,ind]))
    return p0

## Markov and Markov Chains

Markov chains have been introduced by the Russian mathematician Andrei Andreyevich Markov in the early 1900s.



## Introduction

<div class="alert alert-success" align="center">
    The system is `evolving` randomly in time
</div>


A system at time $t=0,1,2,\cdots$
The system can be in one state of a collection of possible states, e.g. **$S$={Happy,So-so,Blue}**
The observation of the system is considered as an experience whose (random) result is the state’s system, so called stochastic process.



##Definition

A discrete time markov chain is a stochastic process modeling a sequence of random variables within a system. The likelihood of the next random variable in the sequence only depends on the current state. 

Formally, given a sequence of events $X_0,X_1,... X_n$ the probability of transitioning to state $i_n$ can be written as:

$$P\left\{X_n=i_n| X_0=i_0,...,X_{n-1}=i_{n-1}\right\} = P\left\{X_n=i_n | X_{n-1}=i_{n-1} \right\}$$

A stochastic matrix describes the dynamics of a Markov chain $\{X_n\}$ that takes values in the state space $S$.

Formally, we say that a discrete time stochastic process $\{X_n\}$ taking values in S is a Markov chain with stochastic matrix $P$ (called **transtition matrix**) if 
$$   {\cal P}\{X_{n+1}=j|X_n=i\}=P[i,j] $$

for any $t\ge0$ and $i,j\in S$; here $\cal P$ means probability.


## examples :

    – state of an engine (working, not working)
    – weather (rain, cloud, snow, sun)
    – robot’s position on a grid
<p>
<div class="alert alert-success" align="center">
    What kind of experience do you have about Markov property? 
</div>


## Stochastic Matrices

A stochastic matrix (or Markov matrix) is an n×n square matrix $P=P[i,j]$ such that

each element $P[i,j]$ is nonnegative, and each row $P[i,⋅]$ sums to one

Let $S:=0,\cdots,n$

Evidently, each row $P[i,⋅]$ can be regarded as a distribution (probability mass function) on $S$.

##Example (Drunkard walk)

A random walk on the number line where, at each step, the position may change by +1 or −1 with equal probability. From any position there are two possible transitions, to the next or previous integer. The transition probabilities depend only on the current position, not on the manner in which the position was reached. For example, the transition probabilities from 5 to 4 and 5 to 6 are both 0.5, and all other transition probabilities from 5 are 0. These probabilities are independent of whether the system was previously in 4 or 6.

Suppose the the drunk man will fall down valley if he go 10 steps straightly toward east. And his first step is toward east and never go west if he is back to the intial position.


In [4]:
P=np.zeros((11,11))
P=np.matrix(P)
P[0,1]=P[10,10]=1.
for i in np.arange(1,10):
    P[i,i-1]=P[i,i+1]=1/2.

In [5]:
P

matrix([[ 0. ,  1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
        [ 0.5,  0. ,  0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0.5,  0. ,  0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0.5,  0. ,  0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0.5,  0. ,  0.5,  0. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0. ,  0.5,  0. ,  0.5,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0. ,  0. ,  0.5,  0. ,  0.5,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.5,  0. ,  0.5,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.5,  0. ,  0.5,  0. ],
        [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.5,  0. ,  0.5],
        [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ]])

In [5]:
n=np.arange(np.size(P[0,]))
printP2(P,n)

In [6]:
printP2(P**20,n)

In [13]:
printP2(P**1000,n)

In [15]:
printP2(P**1001,n)

## Discussions

1. How do you explain the reason why the values at the $P[0,0]$ of the last results are so different with respect to anther? 
2. Eventually, the drunkard would fall down the valley, refenence the following stable discussion.

In [10]:
StableDist(P)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [13]:
printP2(P**100,n)

In [14]:
printP2(P**1001,n)

##Question:

What's your conclusion about the last two results?

## Note:
Numpy provides two kinds of data type to store vector/matrix data, **array() and matrix()**. However, there are some differences between these types, especially the algebraic calculation.

<h3> Drunkard Example again</h3>
Suppose that the state "0"  also repreents falling valley. Reconsider the example again.

In [16]:
P2=P
P2[0,0]=1.;P2[0,1]=0.;
printP2(P2,n)

In [17]:
printP2(P2**1000,n)

In [13]:
printP2(P2**1001,n)

In [31]:
StableDist(P)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

<h3> Note </h3>
Matrices can be treated as a 2D values (data). However, matrix operations are different from general value arithmatic operations.  For instance:
$ M\times M=0$ does not imply $M=0$ for matrix $M$. 

In [4]:
A=np.array([[1,-1],[1,-1]])
B=np.matrix(A)
A,B

(array([[ 1, -1],
        [ 1, -1]]), matrix([[ 1, -1],
         [ 1, -1]]))

In [5]:
printP(A*A)

In [6]:
printP(B*B)

## Example (Lecture or others)

Arnorld, a student in the class, would be in one of four states:

    1. learning
    2. watch his facebook,
    3. write exercise or lab report,
    4. dozing off.

Every ten minutes, Arnold can change his activity or continue the current one. Suppose that the behavior of Arnold's changing state is a process without memory.

    - When he dozes off, there is 9 chances over 10 that he will not wake up the next ten minute, otherwise 1 chance over 10 that he will wake up and listen what he had lost.
    - When he wakes up, there is 1 chance over 3 that listens lecture, and 1 chance over 3 that logins his facebook, and 1 chance over 3 that will write lab report;
    - when teacher ask to him shutdown his cell phone, there is 3 chances over 5 that he will fall in asleep, and 2 chances over 5 that he will write his lab report.
    - when teacher stop his writing staff, there is 1 chances over 4 that he will attend the lecture listening, and 1 chances over 2 that he will doze off.



# Example (continued)

**State $S$**: 1 for listening, 2 for using cell phone, 3 for writing, and 4 for dozzling.

**The first state**: 1

**Question**: After ten minutes, in what state is Arnold we can predict? How about 20 minutes? and so on?


##Answer (continued)

After ten minutes,

1. $1\to1$ (still listening to the lecture): 1/3
2. $1\to2$: 1/3
3. $1\to3$: 1/3
4. $1\to4$: 0



##Example (continued)

After the first result, the transition states from any state could be any state in $S$; the following calculation shows the probability, staring from state 1 to any states and back to state again:
$$
1 \to [1,2,3,4] \to 1\\
   P(X_2=1|X_0=1)=\sum_{i\in S}P(X_1=i|X_0=1)\times P(X_2=1|X_1=i)
$$

Above result describes the case that Arnold still awake and keeps on listening after two time units elapsed.

<h3>Symbols</h3>

$P(X_{n+1}=j|X_n=i)$: the probability of being in $i$-state at time $n+1$ given by condition which is in state $i$ at time $n$. 

##Question:

1. Does this mean that the person always awakes at the first twenty minutes?
2. How many changes does this person awake and listen to the lectecure during two hours?

<div class="alert alert-failed"  align="center">

The case becomes more complicated while time elapses!

</div>

The probability transtion matrix would do much help!

In [18]:
P1=np.matrix([[1/3.,1/3.,1/3.,0],[0,0,2/5.,3/5.],[1/4.,1/4.,0,1/2.],[1/10.,0,0,9/10.]])

In [66]:
printP(P1)

In [19]:
printP(P1**10)

In [27]:
StableDist(P1)

array([[ 0.13602015,  0.06297229,  0.07052897,  0.73047859]])

<div class="alert alert-success" align="center">
<b>Answer for last question<b>: Only about <code>2</code> chances over 10, he is still listening after 20 minutes.
</div>

<h2>Note</h2>
$$P(X_2=1|X_0=1)= \sum_i P(X_2=1|X_1=i)P(X_1=i|X_0=1)=\sum_i P(X_1=1|X_0=i)P(X_1=i|X_0=1)=P^2[1,1]$$

In [69]:
printP(P1**10)

In [70]:
printP(P1**100)

<div class="alert alert" align="center">
How about the last two computed results? 
</div>

## Observation

While at the (large) $n$ step, the transtion probability seems to be distributed as constant as follows:

$$\pi_n=(p_1,p_2,p_3,p_4)^{t=n}$$

Then the transtion probability to the next step should be

1. state 1: $p_1*p_{11}+p_2*p_{21}+p_3*p_{31}+p_4*p_{41}(\sim p_1)$
$$   
   P(X_{n+1}=1) = P(X_n=1) P(X_{n+1}=1|X_n=1)+P(X_n=2) P(X_{n+1}=1|X_n=2)+\cdots+P(X_n=4) P(X_{n+1}=1|X_n=4) 
$$
2. states $i=2,3,4$: $p_1*p_{1i}+p_2*p_{2i}+p_3*p_{3i}+p_4*p_{4i}(\sim p_i)$
3. $$ (p_1,p_2,p_3,p_4)^{n+1}=(p_1,p_2,p_3,p_4)^{n}\times P$$

This implies: $$ \pi_{n+1}=\pi_n\times P$$ if time $n$ is large enough (eventually). This is stable if the following exists:
$$\pi=\lim_{n\to\infty}\pi_{n+1}=\lim_{n\to\infty}\pi_n\times P=\pi P$$


## Tools for evaluate stable $\pi$

NumPy/SciPy is the best choice for computing Linear Algebra and for computing transition matix!


## Example

Physicians who diagnose asymptomatic gallstones are faced with the decision to either immediately remove the gall bladder to prevent possible life-threatening complications or to postpone surgery until complications do occur. What is the long-term trend of each strategy?

        A      C    R     W     D
    A  0.95  0.04   0     0    0.01 
    C   0      0   0.995  0    0.005
    R   0      0   0.09  0.90  0.01 
    W   0      0   0     0.99  0.01
    D   0      0   0      0     1 

Where the state is one of the follows:

    A (1): Asymptomatic gallstone; postpone surgery from 4-month delay with 0.95 probability;
    C (2): cholecystitis or biliary complications; will require surgery with 0.04 probability;
    D (5): natual death state; with probability 0.01 due to age
    R (3): Recovery state;
    W (4): well state; 99% well recovery and 1% to death

Ninety percent of the patients move onto the well state (W) while 9% stay in the recovery state each year and 1% die of natural causes. If the disease progresses and becomes symptomatic, then surgery is performed with a risk of death from complications due to surgery of 0.005.
In [14]:



In [28]:
P2=np.matrix([[0.95,0.04,0,0,0.01],[0,0,0.995,0,0.005],[0,0,0.09,0.9,0.01],[0,0,0,0.99,0.01],\
              [0,0,0,0,1]])
states=['A','C','R','W','D']
printP2(P2,states)

In [29]:
#np.set_printoptions(precision=3)
#numpy.set_printoptions(formatter={'float': lambda x: str(x)})
printP2(P2**3,states)

In [30]:
printP2(P2**30,states)

## Appendix

**Definition**

An $n×k$ matrix is a rectangular array $A$ of numbers with $n$ rows and $k$ columns:

\begin{split}A = \left[ \begin{array}{cccc} a_{11} & a_{12} & \cdots & a_{1k} \\ a_{21} & a_{22} & \cdots & a_{2k} \\ \vdots & \vdots & & \vdots \\ a_{n1} & a_{n2} & \cdots & a_{nk} \end{array} \right]\end{split}

$A$ is called sqrare matrix if $n=k$.

**Definition**

Let $P$ be an $n×n$ square matrix

a. If $\lambda$ is scalar and $\vec v$ is a non-zero vector in $\mathbb{R}^n$ such that $\mathbb{P\vec v=\lambda \vec v}$, then we say that $\lambda$ is a right eigenvalue of $P$, and $\vec v$ is a right eigenvector

b. If $\lambda$ is scalar and $\vec v$ is a non-zero vector in $\mathbb{R}^n$ such that $\mathbb{\vec v P=\lambda \vec v}$, then we say that $\lambda$ is a left eigenvalue of $P$, and $\vec v$ is a left eigenvector

<b>Here, we use left {eigenvalues, eigenvectors} to describe the stable property for $P$.</b>



**Theorem**
Let $P$ be an $n×n$ Transition matrix. 1 is an eigenvalue since
$$ P\cdot[1,1,\cdots,1]^t=\left[\sum_i^n p_{1i},\cdots,\sum_i^n p_{ni}\right]=[1,1,\cdots,1]^t$$

**Theorem**

a. $\vec v P=\lambda \vec v$ impies $\lambda^m$ is eigenvalue of $P^m$ with the same eigenvector:

$$\vec v P^m=(\vec v P) P^{m-1}=\lambda \vec v P^{m-1}=\lambda^2 \vec v P^{m-2}=\cdots= \lambda^m\vec v $$

**Theorem**
Every left eigenvalue $\lambda_j$ satisfies $|\lambda_j|\le1$
$$ \lambda_j^m \vec v = \sum_i^n v_i p^m_{ij} \\
   |\lambda_j^m|\cdot ||\vec v|| \le \sum_i^n |v_i| p_{ij} \\
   |\lambda_j^m|  \le \sum_i^n  p_{ij}\le C \\
$$   
This proves the theorem since the last result would holds for every $m\ge1$.
   

## Example

**Definition**

Suppose that $P$ is a $2x2$ transition matrix, $P$, as follows:

\begin{split}P = \left[ \begin{array}{cc} p_{11} & p_{12}\\ p_{21} & p_{22} \end{array} \right]\end{split}


**Facts**

1. If $p_{12}=p_{21}=0$ $\to$ 2 recurrent states and $\lambda=1$ with multiplicity 2.
2. If $p_{12}=p_{21}=1$ $\to$ periodic and eigenvalues are 1 and $\lambda=-1$ (otherwise $|\lambda|<1$).


##Neumann's Theorem

If $∥A^k∥\lt 1$ for some $k∈\mathbb{N}$, then $I−A$ is invertible, and

\begin{split} (I - A)^{-1} = \sum_{k=0}^{\infty} A^k \end{split} where \begin{split} \| A \| := \max_{\| x \| = 1} \| A x \| \end{split}


## Properties of MC

1. A state $j$ is said to be **accessible** from a state $i$ if $ P^n(i,j)>0$ for some $n\ge0$. 
2. Periodic: A state $ i$ has **period** $k$ if any return to state $i$ must occur in multiples of $k$ time steps. If $k = 1$, then the state is said to be *aperiodic*
3. Recurrence: A state $i$ is said to be *transient* if, given that we start in state $i$, there is a non-zero probability that we will never return to $i$.  A state $i$ is said to be *recurrent* if and only if the expected number, starting from $i$, back to $i$ is infinite.
$$\text{ recurrent if } \sum_{n\ge 1}P_{i,i}^n=\infty;\\
  \text{ transient if } \sum_{n\ge 1}P_{i,i}^n<\infty;\\                       
$$
4. A state $i$ is called *absorbing* if it is impossible to leave this state.
5. Ergodicity: A state $i$ is said to be ergodic if it is aperiodic and positive recurrent. In other words, a state i is ergodic if it is recurrent, has a period of 1 and it has finite mean recurrence time. If all states in an irreducible Markov chain are ergodic, then the chain is said to be ergodic.
6. $\pi$ is called stationary if
   
$$
   \pi=[\pi_1,\cdots,\pi_n], \pi_i\ge0; \\
   \sum_{i\in S}\pi_i=1;\\
   \pi=\pi P
$$ 



## Theorem
An irreducible chain has a stationary distribution if and only if all of its states are positive recurrent, i.e.
$$ \pi=\pi P$$

##Note
An irreducible aperiod Markov chain satisfies:
$$ \pi=\pi P \\
   \to \pi(I_n-1\cdot P)=0$$
   This means $\pi$ is the eigenvector of $P$ with respect to the eigenvalue <font color="red">"$1$"</font>.   <br>  
   <img src="images/invariant.png">   


In [7]:
B=np.matrix([[0.4,0.6],[0.2,0.8]])
printP(B)

In [9]:
evals, evecs =sp.linalg.eig(B,left=True,right=False)

evals=np.real(evals)
evals

array([ 0.2,  1. ])

In [10]:
ev0=evecs[:,1];ev0

array([-0.31622777, -0.9486833 ])

In [11]:
ev0=ev0/sum(ev0);ev0

array([ 0.25,  0.75])

In [ ]:
ev1=StableDist(B)
ev1

In [14]:
ev1*B

matrix([[ 0.25,  0.75]])

## Procedure for Evaluating $\pi$

1. Find out all the eigenvalues of $P$ with eigenvales repectively; 

2. the eigenvector with respect to eigenvale 1 is the stable distribution, $\pi$, that  we want to find.

## By SciPy

1. Find eigenvalues by <br>
   <font color="brown">eigvals,eigvecs=scipy.linalg.eig(P,left=True,right=False)</font>

2. Suppose that eigvec = eigvec[:,i] is the eigenvector with respect to eigenvalue1. It is the stable distribution, $\pi$ if eigenvec is unit vector; otherwise, $\pi$ is <font color="brown">eigvec/sum(eigvec)</font> since total sum of transition probability is equal to 1.

In [20]:
A = np.matrix([[0.7,0.2,0.1],[0,0.5,0.5],[0.,0.9,0.1]])
printP(A)

In [21]:
printP(A**1000)

In [16]:
printP(A**2000)

In [22]:
evals, evecs =sp.linalg.eig(A,left=True,right=False)

evals=np.real(evals)
evals

array([ 0.7,  1. , -0.4])

In [24]:
ev0=evecs[:,1]
ev0

array([ 0.        ,  0.87415728,  0.48564293])

In [25]:
ev0=ev0/sum(ev0);ev0

array([ 0.        ,  0.64285714,  0.35714286])

In [36]:
eps=1e-6
ind=evals[:]>1.-eps
#evals[:,ind]
evecs[:,ind]/sum(evecs[:,ind])

array([[ 0.        ],
       [ 0.64285714],
       [ 0.35714286]])

In [26]:
StableDist(A)

array([[ 0.        ,  0.64285714,  0.35714286]])

##Problem

Suppose that the climate record is as follows (one-day transition):

           cloud  sun rain  snow
    cloud   0.6   0.2  0.2    0
     sun    0.7   0.3    0    0
    rain    0.55    0  0.4  0.05
    snow    0       0  0.5  0.5

What about the climate of tomorrow, and the day after tomorrow? Guess where the place locates. How to introtruce the climate information for travellers?


## Frog on the 7 lily pad

A frog hops about on 7 lily pads. The numbers next to arrows show the probabilities with which, at the next jump, 
he jumps to a neighbouring lily pad (and when out-going probabilities sum to less than 1 he stays where he is with 
the remaining probability).
<p>
<img src="images/frog.png">


## Challenges

    a) Starting in state 1, what is the probability that we are still in state 1 after 3 steps?
    b) after 5 steps?
    c) after 100 steps (or eventually)?



In [17]:
P=np.matrix([[0,1,0,0,0,0,0],
             [0,1/2.,1/2.,0,0,0,0],
             [1/2.,0,1/2.,0,0,0,0],
             [0,0,1/4.,1/2.,1/4.,0,0],
             [0,0,0,0,0,1/2.,1/2.],
             [0,0,1,0,0,0,0],
             [0,0,0,0,0,0,1]])
printP(P)

In [17]:
printP(P*P*P)

In [18]:
printP(P**5)

In [19]:
P000=P**100
P000[0,0]

0.20000000000000001

In [19]:
printP(P**1000)

## Markov Chain Model for Baseball

        
     TABLE 1: RUNNERS AND OUTS COMBINATIONS

Runners: 0(none)1     2     3     12     13     23     123

         0: (0,0)[1]  (1,0)[2]  (2,0)[3]  (3,0)[4]  (12,0)[5]  (13,0)[6]  (23,0)[7]  (123,0)[8]
    Outs 1: (0,1)[9]  (1,1)[10] (2,1)[11] (3,1)[12] (12,1)[13] (13,1)[14] (23,1)[15] (123,1)[16]
         2: (0,2)[17] (1,2)[18] (2,2)[19] (3,2)[20] (12,2)[21] (13,2)[22] (23,2)[23] (123,2)[24]

 Three outs state [25]

There are 25 states, in other words, the transition matrix, $P$, is a $25\times25$ matrix.


## Markov Chain Model for Baseball

<table border="1" cellpadding="2" cellspacing="2" width="70%">
<tbody>
<tr>
<td align="center" valign="top">no.<br>
</td>
<td align="center" valign="top">state<br>
</td>
<td align="center" valign="top">no.<br>
</td>
<td align="center" valign="top">state<br>
</td>
<td align="center" valign="top">no.<br>
</td>
<td align="center" valign="top">state<br>
</td>
</tr>
<tr>
<td align="center" valign="top">1<br>
</td>
<td align="center" valign="top">(0,0)<br>
</td>
<td align="center" valign="top">9<br>
</td>
<td align="center" valign="top">(0,1)<br>
</td>
<td align="center" valign="top">17<br>
</td>
<td align="center" valign="top">(0,2)<br>
</td>
</tr>
<tr>
<td align="center" valign="top">2<br>
</td>
<td align="center" valign="top">(1,0)<br>
</td>
<td align="center" valign="top">10<br>
</td>
<td align="center" valign="top">(1,1)<br>
</td>
<td align="center" valign="top">18<br>
</td>
<td align="center" valign="top">(1,2)<br>
</td>
</tr>
<tr>
<td align="center" valign="top">3<br>
</td>
<td align="center" valign="top">(2,0)<br>
</td>
<td align="center" valign="top">11<br>
</td>
<td align="center" valign="top">(2,1)<br>
</td>
<td align="center" valign="top">19<br>
</td>
<td align="center" valign="top">(2,2)<br>
</td>
</tr>
<tr>
<td align="center" valign="top">4<br>
</td>
<td align="center" valign="top">(3,0)<br>
</td>
<td align="center" valign="top">12<br>
</td>
<td align="center" valign="top">(3,1)<br>
</td>
<td align="center" valign="top">20<br>
</td>
<td align="center" valign="top">(2,3)<br>
</td>
</tr>
<tr>
<td align="center" valign="top">5<br>
</td>
<td align="center" valign="top">(12,0)<br>
</td>
<td align="center" valign="top">13<br>
</td>
<td align="center" valign="top">(12,1)<br>
</td>
<td align="center" valign="top">21<br>
</td>
<td align="center" valign="top">(3,2)<br>
</td>
</tr>
<tr>
<td align="center" valign="top">6<br>
</td>
<td align="center" valign="top">(23,0)<br>
</td>
<td align="center" valign="top">14<br>
</td>
<td align="center" valign="top">(13,1)<br>
</td>
<td align="center" valign="top">22<br>
</td>
<td align="center" valign="top">(12,2)<br>
</td>
</tr>
<tr>
<td align="center" valign="top">7<br>
</td>
<td align="center" valign="top">(123,0)<br>
</td>
<td align="center" valign="top">15<br>
</td>
<td align="center" valign="top">(23,1)<br>
</td>
<td align="center" valign="top">23<br>
</td>
<td align="center" valign="top">(13,2)<br>
</td>
</tr>
<tr>
<td align="center" valign="top">8<br>
</td>
<td valign="top"><br>
</td>
<td align="center" valign="top">16<br>
</td>
<td align="center" valign="top">(123,1)<br>
</td>
<td align="center" valign="top">24<br>
</td>
<td align="center" valign="top">(23,2)<br>
</td>
</tr>
<tr>
<td colspan="4" valign="top"><br>
</td>
<td align="center" valign="top">25<br>
</td>
<td align="center" valign="top">(X,3)<br>
</td>
</tr>
</tbody>
</table>

where (xyz,out) means (runner(s) on 'x,y,z'-bases, out(s)).

##Note1

Not all the tansition from state $i$ to state $j$ could occur, i.e. there are some $p_{ij}=0$ for certain $i,j$.
For instance, the transition from (0,0), state 1, to (0,2), state 17, is impossible.



## Note 2

Data from 2009 MLB postseason: there are 560 occurences for state 1, (0,0) and


                    Times
    (0,0) -> (0,0)    13
             (1,0)   123
             (2,0)    26
             (3,0)     1
             (0,1)   397

This shows that it is more difficulty to get a "triple" than home run!


In [20]:
print(1/560.);print(13/560.)

0.0017857142857142857
0.023214285714285715


##Note 3

state 25 means that it is an absorbing state, i,e. no one can come out while entering this state. 
Then $$ P=\left(\matrix{ A_{24\times24} &B_{24\times1}\\0_{1\times24} &1}\right)$$


Transition matrix for 2009 MLB Postseason


<img src="images/mlb2009-1.png">

 The data in grey color is zero. The elements of left lower triangle are almost being zero since it is impossible to move from (0,0) to there! 

## Facts

1. $$P^2=\left(\matrix{&A ,&(I+A)B \cr &0 ,&I}\right) \\
     P^n=\left(\matrix{&A ,&(I+A+\cdots+A^{n-1})B \cr &0 ,&I}\right)
   $$
2. Fundamental matrix $W=(I-A)^{-1}$
   $$\lim_{n\to\infty}P^n=\left(\matrix{&A ,&W B \cr &0 ,&I}\right)$$

## How many are there hitters until the game over?

From the definition of $A_{24\times24}$, the expected sum of hitters from $i$-state to $j$states is

$$ 1\cdot A^0_{ij}+1\cdot A_{ij}+1\cdot A^2_{ij}+1\cdot A^3_{ij}+\cdots = W_{ij}$$





## Fundamental Matrix

<img src="images/fundamental.png" width=90%>


##Question## 
How many would hitter be in half inn from the following data (2009 postseason)?

## Values of elemnts in the first row of $W$
<font size="1px">
$W_{1,1}=1.036,W_{1,2}=0.234,W_{1,3}=0.059,W_{1,4}=0.004,W_{1,5}=0.067,
W_{1,6}=0.018, W_{1,7}=0.016, W_{1,8}=0.014$<br>
$W_{1,9}=0.774,W_{1,10}=0.293,W_{1,11}=0.103,W_{1,12}=0.016,W_{1,13}=0.119,
W_{1,14}=0.028, W_{1,15}=0.026, W_{1,16}=0.04$<br>
$W_{1,17}=0.606,W_{1,18}=0.34,W_{1,19}=0.149,W_{1,20}=0.038,W_{1,21}=0.162,
W_{1,22}=0.054, W_{1,23}=0.039, W_{1,24}=0.068$<br>
</font>

## Question

Suppose that in the bottom of the fifth inning, the team A is still two runs behind but there are two runners on base 2 and 3 . Now the pitcher is at bat next. How do you to make decision if you were the manager? 


## Discussion

$$\sum_{j}W_{7,j}=4.530, \sum_{j}W_{15,j}=3.171, \sum_{j} W_{24,j}=1.738$$

## Another Question

The most concerned is how about the expected score.

For instance, the expected score (1,1) one step can be calculated  by the following:
$$ R_{1,1}^{1s}=1\times P_{1,1}+0\times(1-P_{1,1})=0.023$$
i.e. home run in this case.

##Another Example
 
The case of one step from state 18 (1.2), one on base and 2 outs:

                Next State    score(s)
     18 (1,2)    17 (0,2)        2
                 18 (1,2)        1
                 19 (2,2)        1
                 20 (3,2)        1
 
And the Expected score is:
$$ R_{18,1}^{1s}= 2\times P_{18,17}+1\times (P_{18,18}+P_{18,19}+P_{18,20})=0.13$$

## Matrix $R^{1s}$
<img src="images/R.png">

## Run Potential Matrix

$RP=W\times R=(W_{i,j})(R^{1s}_{j,1})$

i.e. Expected scores in one game = expected hitter $\times$ expected scores


##Data of $W\times R$   

              RP(1,1)   RP(2,1)   RP(3,1)   RP(4,1)   RP(5,1)   RP(6,1)  RP(7,1)   RP(8,1)
      0 out   0.462     0.873     1.004     1.675     1.398     1.679    1.853     1.275 
              RP(9,1)   RP(10,1)  RP(11,1)  RP(12,1)  RP(13,1)  RP(14,1) RP(15,1)  RP(16,1)
      1 out   0.263     0.431     0.628     1.280     0.759     1.342    1.348     1.114
              RP(17,1)  RP(18,1)  RP(19,1)  RP(20,1)  RP(21,1)  RP(22,1) RP(23,1)  RP(24,1)
      2 out   0.126     0.267     0.332     0.280     0.498     0.377    0.533     0.613     

## Tseng's Playbook

曾紀恩被人所熟知的戰術 : 在無人出局一壘有人的狀態下,命令打者以犧牲短打來將跑者送到二壘。二壘有人一出局後的兩個打席,若有一支安打就有機會得分。相對地,無人出局一壘有人,想要得分,好像要在三個打席中出現兩支安打才行。

Is it reasonable?

Answer: Tseng's trajedy gets 0.628 (**RP(2,1)**, 1 0ut and one on two base) smarller than 0.873 (**RP(2,1)**, no out and one on base 1). 

In [22]:
class discreteRV(object):

    def __init__(self, q):
        self._q = q
        self.Q = cumsum(q)

    def get_q(self):
        return self._q

    def set_q(self, val):
        self._q = val
        self.Q = cumsum(val)

    q = property(get_q, set_q)

    def draw(self, k=1):
        return self.Q.searchsorted(uniform(0, 1, size=k)) 



##Example 1

Consider a worker who, at any given time $t$, is either unemployed (state 0) or employed (state 1)

Let’s write this mathematically as $X_t= 0 \text{ or }1$

Suppose that, over a one month period,

* An unemployed worker finds a job with probability $\alpha\in(0,1)$
* An employed worker loses her job and becomes unemployed with probability $\beta\in(0,1)$

The stochastic matrix is $$ P=\left(\matrix{\alpha &1-\alpha \\ 1-\beta &\beta}\right)$$

$\psi=(p,1-p)$ where represents probability at state being $0,1$ respectively.

For instance, $p=0.1$


In [23]:
psi=(0.1,0.9)
d = discreteRV(psi)
d.draw(10)



array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [24]:
def sample_path(P, init=0, sample_size=1000): 

    # === set up array to store output === #
Values of elemnts in the first row of W W1,1=1.036,W1,2=0.234,W1,3=0.059,W1,4=0.004,W1,5=0.067,W1,6=0.018,W1,7=0.016,W1,8=0.014
W1,9=0.774,W1,10=0.293,W1,11=0.103,W1,12=0.016,W1,13=0.119,W1,14=0.028,W1,15=0.026,W1,16=0.04
W1,17=0.606,W1,18=0.34,W1,19=0.149,W1,20=0.038,W1,21=0.162,W1,22=0.054,W1,23=0.039,W1,24=0.068

    X = np.empty(sample_size, dtype=int)
    if isinstance(init, int):
        X[0] = init
    else:
        X[0] = discreteRV(init).draw()
    n = len(P)
    P_dist = [discreteRV(P[i,:]) for i in range(n)]

    # === generate the sample path === #
    for t in range(sample_size - 1):
        X[t+1] = P_dist[X[t]].draw()
    return X



In [25]:
P = np.array([[.4, .6], [.2, .8]])

In [26]:
s = sample_path(P, init=(0.5, 0.5), sample_size=100000)
(s == 0).mean()



0.25241999999999998

In [27]:
P = np.array([[.4, .6], [.2, .8]])